### ISSUE TITLE
The requested module '@minswap/sdk' does not provide an export named 'BlockfrostAdapter'

### ISSUE THREAD

**Issue by Mi88ir** [minswap/sdk#20]
Trying to use the examples provided in the repo but I keep getting this error with both historical and current price examples. 

Currently using NodeJs v16.17.0 

I have tried both require and import ways - both are throwing the same error. 

Any fix for this or is there something I am doing wrong?

![image](https://github.com/minswap/sdk/assets/30632565/a137d2cb-03c2-4cff-9ba3-3e0fbbc91646)

**Comment by longngn** [comment]
fix in 0.2.1-beta version
