### ISSUE TITLE
Cannot find module '@minswap/sdk' or its corresponding type declarations.

### ISSUE THREAD

**Issue by gotbitlabs** [minswap/sdk#21]
No typing for this module. There is no possibility to import this package

**Comment by longngn** [comment]
> No typing for this module. There is no possibility to import this package

have you installed the latest version and set `"type": "module"` in your package.json?

**Comment by ndtr2000** [comment]
@longngn I'm getting the same error. I'm using typescript
This is my ts.config file
```typescript
{
    "compilerOptions": {
        "target": "ES2022",
        "module": "ES2022",
        "moduleResolution": "node",
        "lib": ["ES2022", "DOM"],
        "outDir": "build-tsc",
        "skipLibCheck": true,
        "esModuleInterop": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "noImplicitOverride": true,
        "noUnusedParameters": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noFallthroughCasesInSwitch": true
    },
    "ts-node": {
        "esm": true,
        "experimentalSpecifierResolution": "node"
    },
    "exclude": ["build"]
}
```

I've already included `"type": "module",` in my package.json file

**Comment by KeilFelix** [comment]
I looked through the node modules and had to include 'build'. As a Node.Js noob this took me 2 days to figure out. So please try out
`import { BlockfrostAdapter } from "@minswap/sdk/build";`

**Comment by KeilFelix** [comment]
@longngn my suggestion did also not work because then I get a runtime error ERR_PACKAGE_PATH_NOT_EXPORTED.
With your suggestion it works fine. 👍

Now I could get the sample to run successfully.

**Comment by ndtr2000** [comment]
Thanks @longngn @KeilFelix, I use @longngn 's method and it worked
